[package]
name = "aliyun-log-sdk-protobuf"
version = "0.1.1"
edition = "2021"
authors = ["Aliyun Log Service"]
description = "A crate to serialize log data for Aliyun Log Service."
license = "MIT"
keywords = ["aliyun", "sls", "protobuf", "alibabacloud"]
documentation = "https://docs.rs/aliyun-log-sdk-protobuf"
homepage = "https://github.com/aliyun/aliyun-log-rust-sdk/tree/master/protobuf"
repository = "https://github.com/aliyun/aliyun-log-rust-sdk/tree/master/protobuf"
autobenches = false

[dependencies]
getset = "0.1.7"
quick-protobuf = "0.8.1"
thiserror = "2.0.20"

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }
prost = "0.14.4"

[[bench]]
name = "proto"
harness = false
