from typing import Any
from ._native import ProducerConfig, LogstoreWriter

class Producer:
    def __init__(self, config: ProducerConfig) -> None: ...
    def writer(self, project: str, logstore: str) -> LogstoreWriter: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Producer: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...
