name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings
    - name: Build
      run: cargo build --workspace --all-features --verbose
    - name: Run tests
      run: cargo test --workspace --verbose --lib
    - name: Run doc test
      run: cargo test --workspace --verbose --doc
    - name: Check documentation warnings
      env:
        RUSTDOCFLAGS: -D warnings
      run: cargo doc --workspace --all-features --no-deps
    - name: build integration tests
      run: cargo test --test '*' --no-run
    - name: Dependency security audit
      uses: rustsec/audit-check@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
